// Generated by CHATGPT
// Prompt: Give me the minimal code necessary to list workorders based on the schema provided.Needs to be testable via curl.

package workorder

import "errors"

var (
	ErrNotFound = errors.New("work order not found")
)
