// Generated by CHATGPT
// Prompt: Give me the minimal code necessary to list workorders based on the schema provided.Needs to be testable via curl.

package workorder

import (
	"encoding/json"
	"net/http"

	"github.com/go-chi/chi/v5"
)

type Handler struct {
	service Service
}

func NewHandler(s Service) *Handler {
	return &Handler{service: s}
}

func (h *Handler) RegisterRoutes(r chi.Router) {
	r.Get("/", h.List)

}

// GET /workorders
func (h *Handler) List(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	items, err := h.service.List(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(items)
}
