// Generated by CHATGPT
// Prompt: Give me the minimal code necessary to list workorders based on the schema provided.Needs to be testable via curl.
package workorder

import "time"

// WorkOrder represents one row from app.work_orders
type WorkOrder struct {
	ID         string     `db:"work_order_id" json:"id"`
	Code       string     `db:"work_order_code" json:"code"`
	CustomerID string     `db:"customer_id" json:"customer_id"`
	ShopID     string     `db:"shop_id" json:"shop_id"`
	Status     string     `db:"status" json:"status"`
	DamageDate *time.Time `db:"damage_date" json:"damage_date,omitempty"`
	CreatedAt  time.Time  `db:"created_at" json:"created_at"`
}
