// Generated by CHATGPT
// Prompt: Give me the minimal code necessary to list workorders based on the schema provided.Needs to be testable via curl.

package workorder

import "context"

type Service interface {
	List(ctx context.Context) ([]WorkOrder, error)
}

type service struct {
	repo Repository
}

func NewService(r Repository) Service {
	return &service{repo: r}
}

func (s *service) List(ctx context.Context) ([]WorkOrder, error) {
	return s.repo.List(ctx)
}
