-- Citation: Generated by Claude (Anthropic) with prompt:
-- "Help create users and roles tables with constraints and triggers for a PostgreSQL database schema named app, considering using GCP user/password auth."
-- Edited and reviewed by AN-NI HUANG
-- Date: 2025-10-20
-- +goose Up
-- +goose StatementBegin
-- ============================================================================
-- Table: app.roles
-- ============================================================================
CREATE TABLE IF NOT EXISTS APP.ROLES (
  ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  CODE TEXT UNIQUE NOT NULL,
  NAME TEXT NOT NULL,
  IS_SYSTEM BOOLEAN NOT NULL DEFAULT FALSE,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 
  -- Only 'superadmin' is a system role
  CONSTRAINT CK_ROLES_SYSTEM_CODE CHECK ( (IS_SYSTEM = TRUE AND CODE IN ('superadmin')) OR (IS_SYSTEM = FALSE) )
);

-- ============================================================================
-- Table: app.users (direct FK role_id)
-- ============================================================================
CREATE TABLE IF NOT EXISTS APP.USERS (
  ID UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  CODE VARCHAR(10) UNIQUE NOT NULL,
  EMAIL CITEXT UNIQUE NOT NULL,
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT NOT NULL,
  PHONE TEXT,
  IMAGE_URL TEXT,
  PROVIDER TEXT NOT NULL DEFAULT 'firebase',
  EXTERNAL_ID TEXT UNIQUE,
  EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  DEACTIVATED_AT TIMESTAMPTZ,
  DEACTIVATED_BY UUID REFERENCES APP.USERS(ID) ON DELETE SET NULL,
  TOKEN_VERSION INTEGER NOT NULL DEFAULT 1,
  SHOP_ID UUID REFERENCES APP.SHOP(ID) ON DELETE SET NULL,
  ROLE_ID UUID NOT NULL REFERENCES APP.ROLES(ID) ON DELETE RESTRICT,
  CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT CK_USER_EMAIL CHECK (EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'),
  CONSTRAINT CK_USER_PHONE CHECK (PHONE IS NULL OR PHONE ~* '^[0-9]{3}-[0-9]{3}-[0-9]{4}$'),
  CONSTRAINT CK_USER_IMAGE_URL CHECK (IMAGE_URL IS NULL OR IMAGE_URL ~* '^https?://')
);

-- ============================================================================
-- Seed default roles
-- ============================================================================
INSERT INTO APP.ROLES (
  CODE,
  NAME,
  IS_SYSTEM
) VALUES (
  'superadmin',
  'Super Administrator',
  TRUE
),
(
  'admin',
  'Administrator',
  FALSE
),
(
  'adjuster',
  'Adjuster (Insurance Claims)',
  FALSE
),
(
  'bodyman',
  'Bodyman (Repair Technician)',
  FALSE
) ON CONFLICT (
  CODE
) DO NOTHING;

-- ============================================================================
-- Sequence for user code
-- ============================================================================
CREATE SEQUENCE IF NOT EXISTS APP.USER_CODE_SEQ START 1 INCREMENT 1;

-- ============================================================================
-- Functions
-- ============================================================================

-- Generate sequential user code like U-0001
CREATE OR REPLACE FUNCTION app.generate_user_code()
RETURNS varchar AS $$
DECLARE
  next_num int;
BEGIN
  next_num := nextval('app.user_code_seq');
  RETURN 'U-' || lpad(next_num::text, 4, '0');
END;
$$ LANGUAGE plpgsql;


-- Normalize user inputs (trim, case adjustment)
CREATE OR REPLACE FUNCTION app.user_normalize()
RETURNS trigger AS $$
BEGIN
  NEW.email := lower(trim(NEW.email));
  IF NEW.phone IS NOT NULL THEN NEW.phone := trim(NEW.phone); END IF;
  IF NEW.image_url IS NOT NULL THEN NEW.image_url := trim(NEW.image_url); END IF;
  IF NEW.external_id IS NOT NULL THEN NEW.external_id := NULLIF(trim(NEW.external_id), ''); END IF; -- Trim and nullify empty
  NEW.first_name := initcap(trim(NEW.first_name));
  NEW.last_name := initcap(trim(NEW.last_name));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- Set code on insert when blank/NULL
CREATE OR REPLACE FUNCTION app.user_set_code()
RETURNS trigger AS $$
BEGIN
  IF coalesce(NEW.code, '') = '' THEN
    NEW.code := app.generate_user_code();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================================
-- Triggers
-- ============================================================================
DROP TRIGGER IF EXISTS trg_user_normalize ON app.users;
CREATE TRIGGER trg_user_normalize
  BEFORE INSERT OR UPDATE ON app.users
  FOR EACH ROW
  EXECUTE FUNCTION app.user_normalize();

DROP TRIGGER IF EXISTS trg_user_set_code ON app.users;
CREATE TRIGGER trg_user_set_code
  BEFORE INSERT ON app.users
  FOR EACH ROW
  EXECUTE FUNCTION app.user_set_code();

DROP TRIGGER IF EXISTS trg_user_updated_at ON app.users;
CREATE TRIGGER trg_user_updated_at
  BEFORE UPDATE ON app.users
  FOR EACH ROW
  EXECUTE FUNCTION app.set_updated_at();

DROP TRIGGER IF EXISTS trg_roles_updated_at ON app.roles;
CREATE TRIGGER trg_roles_updated_at
  BEFORE UPDATE ON app.roles
  FOR EACH ROW
  EXECUTE FUNCTION app.set_updated_at();


-- ============================================================================
-- Indexes (performance optimization)
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_users_role_id ON app.users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_shop_id ON app.users(shop_id);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON app.users(is_active);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin

-- Drop triggers
DROP TRIGGER IF EXISTS trg_roles_updated_at ON app.roles;
DROP TRIGGER IF EXISTS trg_user_updated_at ON app.users;
DROP TRIGGER IF EXISTS trg_user_set_code ON app.users;
DROP TRIGGER IF EXISTS trg_user_normalize ON app.users;

-- Drop functions
DROP FUNCTION IF EXISTS app.user_set_code();
DROP FUNCTION IF EXISTS app.user_normalize();
DROP FUNCTION IF EXISTS app.generate_user_code();

-- Drop indexes
DROP INDEX IF EXISTS idx_users_is_active;
DROP INDEX IF EXISTS idx_users_shop_id;
DROP INDEX IF EXISTS idx_users_role_id;

-- Drop sequence
DROP SEQUENCE IF EXISTS app.user_code_seq;

-- Drop tables
DROP TABLE IF EXISTS app.users;
DROP TABLE IF EXISTS app.roles;

-- +goose StatementEnd