-- Citation: Generated by ChatGPT with prompt:
-- "Could you Help me check if anything missing in my users table in this two migrations (20251020200253_create_users_and_roles.sql and 20251027193411_update_users_for_gcip_auth.sql) for GCIP authentication?"
-- Edited and reviewed by AN-NI HUANG
-- Date: 2025-10-27
-- +goose Up
-- +goose StatementBegin

-- 1) Remove provider column (GCIP manages externally)
ALTER TABLE APP.USERS DROP COLUMN PROVIDER;

-- 2) Make external_id mandatory
ALTER TABLE APP.USERS ALTER COLUMN EXTERNAL_ID SET NOT NULL;

-- 3) Add last_sign_in_at for audit and analytics
ALTER TABLE APP.USERS
  ADD COLUMN LAST_SIGN_IN_AT TIMESTAMPTZ;

-- 4) Add validation constraints
ALTER TABLE APP.USERS
  ADD CONSTRAINT CK_USER_EXTERNAL_ID_NOT_BLANK CHECK (
    CHAR_LENGTH(EXTERNAL_ID) > 0
  ), ADD CONSTRAINT CK_USER_TOKEN_VERSION_POSITIVE CHECK (
    TOKEN_VERSION >= 1
  ), ADD CONSTRAINT CK_USER_ACTIVE_DEACTIVATED_CONSISTENCY CHECK (
    (IS_ACTIVE = TRUE AND DEACTIVATED_AT IS NULL) OR (IS_ACTIVE = FALSE AND DEACTIVATED_AT IS NOT NULL)
  ), ADD CONSTRAINT CK_USER_FIRST_NAME_NOT_BLANK CHECK (
    CHAR_LENGTH(FIRST_NAME) > 0
  ), ADD CONSTRAINT CK_USER_LAST_NAME_NOT_BLANK CHECK (
    CHAR_LENGTH(LAST_NAME) > 0
  ), ADD CONSTRAINT CK_USER_CODE_LENGTH CHECK (
    CHAR_LENGTH(CODE) BETWEEN 2 AND 10
  );

-- 4.1) Fix CK_USER_EMAIL regex (previous version used \\ which prevented '.' from matching correctly)
ALTER TABLE APP.USERS DROP CONSTRAINT IF EXISTS CK_USER_EMAIL,
  ADD CONSTRAINT CK_USER_EMAIL CHECK (
    EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
  );

-- 5) Function: make external_id immutable after creation
CREATE OR REPLACE FUNCTION app.user_immutable_external_id()
RETURNS trigger AS $$
BEGIN
  IF NEW.external_id IS DISTINCT FROM OLD.external_id THEN
    RAISE check_violation
      USING MESSAGE = 'external_id cannot be changed once set',
            CONSTRAINT = 'ck_user_external_id_immutable';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 6) Function: manage active/deactivated fields and bump token_version 
CREATE OR REPLACE FUNCTION app.user_status_and_role_guard()
RETURNS trigger AS $$
BEGIN
  IF NEW.is_active = FALSE THEN
    IF NEW.deactivated_at IS NULL THEN
      NEW.deactivated_at := NOW();
    END IF;
  ELSE
    NEW.deactivated_at := NULL;
    NEW.deactivated_by := NULL;
  END IF;

  IF (NEW.role_id IS DISTINCT FROM OLD.role_id)
     OR (NEW.is_active IS DISTINCT FROM OLD.is_active) THEN
    NEW.token_version := GREATEST(1, OLD.token_version) + 1; --Recommended by ChatGPT to use GREATEST for safety
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7) Function: normalize fields (nullify empty phone/image_url only)
CREATE OR REPLACE FUNCTION app.user_normalize()
RETURNS trigger AS $$
BEGIN
  NEW.email := lower(trim(NEW.email));
  IF NEW.phone IS NOT NULL THEN NEW.phone := trim(NEW.phone); END IF;
  IF NEW.image_url IS NOT NULL THEN NEW.image_url := trim(NEW.image_url); END IF;
  NEW.external_id := trim(NEW.external_id);
  NEW.phone       := NULLIF(NEW.phone, '');
  NEW.image_url   := NULLIF(NEW.image_url, '');
  NEW.first_name  := initcap(trim(NEW.first_name));
  NEW.last_name   := initcap(trim(NEW.last_name));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 8) Triggers
CREATE TRIGGER trg_user_immutable_external_id
  BEFORE UPDATE ON app.users
  FOR EACH ROW
  EXECUTE FUNCTION app.user_immutable_external_id();

CREATE TRIGGER trg_user_status_and_role_guard
  BEFORE UPDATE ON app.users
  FOR EACH ROW
  EXECUTE FUNCTION app.user_status_and_role_guard();

-- +goose StatementEnd



-- +goose Down
-- +goose StatementBegin

-- 1) Drop new triggers
DROP TRIGGER IF EXISTS trg_user_status_and_role_guard ON app.users;
DROP TRIGGER IF EXISTS trg_user_immutable_external_id ON app.users;

-- 2) Drop added functions
DROP FUNCTION IF EXISTS app.user_status_and_role_guard();
DROP FUNCTION IF EXISTS app.user_immutable_external_id();

-- 3) Restore previous user_normalize
CREATE OR REPLACE FUNCTION app.user_normalize()
RETURNS trigger AS $$
BEGIN
  NEW.email := lower(trim(NEW.email));
  IF NEW.phone IS NOT NULL THEN NEW.phone := trim(NEW.phone); END IF;
  IF NEW.image_url IS NOT NULL THEN NEW.image_url := trim(NEW.image_url); END IF;
  IF NEW.external_id IS NOT NULL THEN
    NEW.external_id := NULLIF(trim(NEW.external_id), '');
  END IF;
  NEW.first_name := initcap(trim(NEW.first_name));
  NEW.last_name  := initcap(trim(NEW.last_name));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 4) Remove constraints added in this migration
ALTER TABLE app.users
  DROP CONSTRAINT IF EXISTS ck_user_code_length,
  DROP CONSTRAINT IF EXISTS ck_user_last_name_not_blank,
  DROP CONSTRAINT IF EXISTS ck_user_first_name_not_blank,
  DROP CONSTRAINT IF EXISTS ck_user_active_deactivated_consistency,
  DROP CONSTRAINT IF EXISTS ck_user_token_version_positive,
  DROP CONSTRAINT IF EXISTS ck_user_external_id_not_blank;

-- 4.1) Restore the original CK_USER_EMAIL regex (kept the double backslash \\ to revert to the initial pattern)
ALTER TABLE APP.USERS
  DROP CONSTRAINT IF EXISTS CK_USER_EMAIL,
  ADD CONSTRAINT CK_USER_EMAIL CHECK (
    EMAIL ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
  );

-- 5) Restore column definitions from previous version
ALTER TABLE app.users ALTER COLUMN external_id DROP NOT NULL;
ALTER TABLE app.users DROP COLUMN last_sign_in_at;
ALTER TABLE app.users ADD COLUMN provider TEXT NOT NULL DEFAULT 'firebase';

-- +goose StatementEnd