-- Citation: Generated by Claude (Anthropic) with prompt: "Help align Go service validation with SQL constraints"
-- Edited and reviewed by AN-NI HUANG
-- Date: 2025-10-19

-- +goose Up
-- +goose StatementBegin

-- 1) Rename existing constraints for consistency
ALTER TABLE APP.SHOP RENAME CONSTRAINT CK_SHOP_PHONE TO CK_SHOP_PHONE_FORMAT;

ALTER TABLE APP.SHOP RENAME CONSTRAINT CK_SHOP_EMAIL TO CK_SHOP_EMAIL_FORMAT;

ALTER TABLE APP.SHOP RENAME CONSTRAINT CK_SHOP_POSTAL TO CK_SHOP_POSTAL_FORMAT;

ALTER TABLE APP.SHOP RENAME CONSTRAINT CK_SHOP_PROVINCE TO CK_SHOP_PROVINCE_WHITELIST;

-- 2) Add blank check constraints for text fields
-- Note: the normalization trigger will TRIM spaces, so blank means length zero after trimming
ALTER TABLE APP.SHOP
    ADD CONSTRAINT CK_SHOP_NAME_NOT_BLANK CHECK (
        CHAR_LENGTH(SHOP_NAME) > 0
    ), ADD CONSTRAINT CK_SHOP_ADDRESS_NOT_BLANK CHECK (
        CHAR_LENGTH(ADDRESS) > 0
    ), ADD CONSTRAINT CK_SHOP_CITY_NOT_BLANK CHECK (
        CHAR_LENGTH(CITY) > 0
    ), ADD CONSTRAINT CK_SHOP_CONTACT_NOT_BLANK CHECK (
        CHAR_LENGTH(CONTACT_NAME) > 0
    );

-- 3) Add code length constraint (minimum 2 characters)
ALTER TABLE APP.SHOP
    ADD CONSTRAINT CK_SHOP_CODE_LENGTH CHECK (
        CHAR_LENGTH(CODE) >= 2
    );

-- 4) Update normalization function to TRIM ALL text fields (match Go service layer)
-- Status is excluded as it's an enum type
CREATE OR REPLACE FUNCTION app.shop_normalize()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.code := UPPER(TRIM(NEW.code));
  NEW.shop_name := TRIM(NEW.shop_name);
  NEW.address := TRIM(NEW.address);
  NEW.city := TRIM(NEW.city);
  NEW.province := UPPER(TRIM(NEW.province));
  NEW.postal_code := UPPER(REPLACE(TRIM(NEW.postal_code), ' ', ''));
  NEW.contact_name := TRIM(NEW.contact_name);
  NEW.phone := TRIM(NEW.phone);
  NEW.email := LOWER(TRIM(NEW.email));
  RETURN NEW;
END;
$$;

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin

-- 1) Restore original normalization function
CREATE OR REPLACE FUNCTION app.shop_normalize()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.province := UPPER(NEW.province);
  NEW.postal_code := UPPER(REPLACE(NEW.postal_code, ' ', ''));
  NEW.code := UPPER(NEW.code);
  NEW.email := TRIM(NEW.email);
  RETURN NEW;
END;
$$;

-- 2) Remove code length constraint
ALTER TABLE app.shop 
    DROP CONSTRAINT IF EXISTS ck_shop_code_length;

-- 3) Remove the blank check constraints
ALTER TABLE app.shop 
    DROP CONSTRAINT IF EXISTS ck_shop_contact_not_blank,
    DROP CONSTRAINT IF EXISTS ck_shop_city_not_blank,
    DROP CONSTRAINT IF EXISTS ck_shop_address_not_blank,
    DROP CONSTRAINT IF EXISTS ck_shop_name_not_blank;

-- 4) Restore original constraint names
ALTER TABLE app.shop 
    RENAME CONSTRAINT ck_shop_province_whitelist TO ck_shop_province;

ALTER TABLE app.shop 
    RENAME CONSTRAINT ck_shop_postal_format TO ck_shop_postal;

ALTER TABLE app.shop 
    RENAME CONSTRAINT ck_shop_email_format TO ck_shop_email;

ALTER TABLE app.shop 
    RENAME CONSTRAINT ck_shop_phone_format TO ck_shop_phone;
-- +goose StatementEnd