-- +goose Up
-- +goose StatementBegin
-- 1) Enum type
CREATE TYPE app.shop_status AS ENUM ('active','inactive');

-- 2) Trigger function for updated_at 
CREATE OR REPLACE FUNCTION app.set_updated_at() RETURNS trigger
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
  SET search_path = app, pg_temp;

-- 3) Main table 
CREATE TABLE app.shop (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         VARCHAR(10)  NOT NULL CONSTRAINT uq_shop_code UNIQUE, 
  shop_name    TEXT NOT NULL,
  status       app.shop_status NOT NULL DEFAULT 'active',
  address      TEXT NOT NULL,        -- street address
  city         TEXT NOT NULL,
  province     CHAR(2)      NOT NULL,        -- AB/BC/ON...
  postal_code  CHAR(7)      NOT NULL,        -- T2P 2B5
  contact_name TEXT NOT NULL,
  phone        VARCHAR(20)  NOT NULL,        -- 403-555-1234
  email        VARCHAR(254) NOT NULL,        -- regular email format

  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

  CONSTRAINT ck_shop_province CHECK (province IN
    ('AB','BC','MB','NB','NL','NT','NS','NU','ON','PE','QC','SK','YT')),
  
  CONSTRAINT ck_shop_postal CHECK (postal_code ~* '^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$'),

  CONSTRAINT ck_shop_phone
    CHECK (phone ~* '^[0-9]{3}-[0-9]{3}-[0-9]{4}$'),  

  CONSTRAINT ck_shop_email
    CHECK (
      email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$' 
    )
);

-- 4) Trigger to auto-update updated_at on row modification
CREATE OR REPLACE TRIGGER trg_shop_updated_at
BEFORE UPDATE ON app.shop
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- A) Drop trigger and table
DROP TRIGGER IF EXISTS trg_shop_updated_at ON app.shop;
DROP TABLE IF EXISTS app.shop;

-- B) Drop trigger function
DROP FUNCTION IF EXISTS app.set_updated_at();

-- C) Drop enum type (no dependents remain after dropping table)
DROP TYPE IF EXISTS app.shop_status;

-- +goose StatementEnd