-- +goose Up
-- +goose StatementBegin
-- 1. Create application schema owned by app_owner
CREATE SCHEMA IF NOT EXISTS APP AUTHORIZATION APP_OWNER;

-- 2. Keep public schema but prevent object creation there
REVOKE CREATE ON SCHEMA PUBLIC FROM PUBLIC;

-- 3. Control who can CONNECT to the database
REVOKE CONNECT ON DATABASE HAVENZSURE FROM PUBLIC;

GRANT CONNECT ON DATABASE HAVENZSURE TO APP_OWNER;

GRANT CONNECT ON DATABASE HAVENZSURE TO APP_USER;

-- 4. Let app_user resolve names inside the app schema
GRANT USAGE ON SCHEMA APP TO APP_USER;

-- 5. Default privileges for future objects created by app_owner( in schema app)
ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO APP_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP GRANT USAGE, SELECT ON SEQUENCES TO APP_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP GRANT EXECUTE ON FUNCTIONS TO APP_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP GRANT USAGE ON TYPES TO APP_USER;

-- 6) put app first in the search_path
ALTER DATABASE HAVENZSURE SET SEARCH_PATH = APP, PUBLIC;

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin

-- 1. Restore search_path
ALTER DATABASE HAVENZSURE RESET SEARCH_PATH;

-- 2. Revoke default privileges for future objects
ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM APP_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP REVOKE USAGE, SELECT ON SEQUENCES FROM APP_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP REVOKE EXECUTE ON FUNCTIONS FROM APP_USER;

ALTER DEFAULT PRIVILEGES FOR ROLE APP_OWNER IN SCHEMA APP REVOKE USAGE ON TYPES FROM APP_USER;

-- 3. Revoke schema/database access
REVOKE USAGE ON SCHEMA APP FROM APP_USER;

REVOKE CONNECT ON DATABASE HAVENZSURE FROM APP_USER;

-- 4. Restore public schema create grant
GRANT CREATE ON SCHEMA PUBLIC TO PUBLIC;

-- 5. Finally drop the app schema (and everything inside it)
DROP SCHEMA IF EXISTS APP CASCADE;

-- +goose StatementEnd