package user

import (
	"time"

	"github.com/google/uuid"
)

// Role represents a role in the system
type Role struct {
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	IsSystem  bool      `json:"-"` // backend-only: protect system roles
	CreatedAt time.Time `json:"-"` // backend-only
	UpdatedAt time.Time `json:"-"` // backend-only
}

// Shop represents a shop
type Shop struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// User represents a system user for internal use
type User struct {
	ID            uuid.UUID  `json:"-"`
	Code          string     `json:"-"`
	Email         string     `json:"-"`
	FirstName     string     `json:"-"`
	LastName      string     `json:"-"`
	Phone         *string    `json:"-"`
	ImageURL      *string    `json:"-"`
	ExternalID    string     `json:"-"` // GCIP UID (immutable)
	EmailVerified bool       `json:"-"`
	IsActive      bool       `json:"-"`
	DeactivatedAt *time.Time `json:"-"`
	DeactivatedBy *uuid.UUID `json:"-"`
	TokenVersion  int        `json:"-"`
	ShopID        *uuid.UUID `json:"-"`
	RoleID        uuid.UUID  `json:"-"`
	CreatedAt     time.Time  `json:"-"`
	UpdatedAt     time.Time  `json:"-"`
	LastSignInAt  *time.Time `json:"-"`

	// Role - each user must have exactly ONE role (enforced by role_id NOT NULL)
	Role Role `json:"-"`

	// Shop - optional shop assignment
	Shop *Shop `json:"-"`
}

// CreateUserInput represents the input data required to create a new user
type CreateUserInput struct {
	Email     string  `json:"email"`
	FirstName string  `json:"firstName"`
	LastName  string  `json:"lastName"`
	Phone     *string `json:"phone,omitempty"`
	ImageURL  *string `json:"imageUrl,omitempty"`
	ShopCode  *string `json:"shopCode,omitempty"` // Frontend passes shop code
	RoleCode  string  `json:"roleCode"`           // Frontend passes role code

	// Internal fields (populated by service, not exposed in JSON)
	EmailVerified bool       `json:"-"` // Always set to false for new users
	ExternalID    string     `json:"-"` // Generated by Firebase Admin SDK
	ShopID        *uuid.UUID `json:"-"`
	RoleID        uuid.UUID  `json:"-"`
}

// UpdateUserInput represents the fields that can be updated for a user
type UpdateUserInput struct {
	FirstName     *string `json:"firstName,omitempty"`
	LastName      *string `json:"lastName,omitempty"`
	Phone         *string `json:"phone,omitempty"`
	ImageURL      *string `json:"imageUrl,omitempty"`
	EmailVerified *bool   `json:"emailVerified,omitempty"`
	ShopCode      *string `json:"shopCode,omitempty"` // Frontend passes shop code
	RoleCode      *string `json:"roleCode,omitempty"` // Frontend passes role code

	// Internal fields (populated by service, not exposed in JSON)
	ShopID *uuid.UUID `json:"-"`
	RoleID *uuid.UUID `json:"-"`
	// IsActive cannot be updated here; use ActivateUser / DeactivateUser methods
}
